# Generated by Django 5.0.6 on 2024-08-02 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_jogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_ativo',
            new_name='is_active',
        ),
    ]
